import "server-only";

import type Anthropic from "@anthropic-ai/sdk";

import { callTool, type ServerTool } from "@/lib/ai/call";
import { MODELS } from "@/lib/ai/models";
import { getAssetLibrary } from "@/lib/ai/asset-library";
import {
  CLASSIFY_ASSETS_V2_PROMPT_VERSION,
  CLASSIFY_ASSETS_V2_SYSTEM,
  CLASSIFY_ASSETS_V2_TOOL,
  buildClassifyAssetsV2UserPrompt,
  classifyAssetsV2OutputSchema,
  type ClassifyAssetsV2Input,
  type ClassifyAssetsV2Output,
} from "@/lib/ai/prompts/classify-assets-v2";
import type { DescribePhotoOutput } from "@/lib/ai/prompts/describe-photos";
import { scrubPiiJson } from "@/lib/ai/scrub";
import {
  applyResidualPlug,
  formatV2ValidationErrorForRetry,
  validateClassifyAssetsV2,
} from "@/lib/ai/validator-v2";
import { isV2WebSearchEnabled } from "@/lib/features/v2-report";

import type { PropertyType } from "@prisma/client";

/**
 * Phase 3 web_search configuration. Constrained to the five retailer
 * domains called out in ADR 0010; the allowlist keeps the model off
 * SEO-farm junk and review-aggregator pages whose "prices" rot fast.
 */
const WEB_SEARCH_TOOL: Anthropic.Messages.WebSearchTool20250305 = {
  type: "web_search_20250305",
  name: "web_search",
  max_uses: 50,
  allowed_domains: [
    "target.com",
    "www.target.com",
    "wayfair.com",
    "www.wayfair.com",
    "homedepot.com",
    "www.homedepot.com",
    "lowes.com",
    "www.lowes.com",
    "amazon.com",
    "www.amazon.com",
    "ikea.com",
    "www.ikea.com",
  ],
};

/**
 * Residual class per PropertyType. Short-term rentals are nonresidential
 * under IRC §168 (transient use); everything else residential uses 27.5yr.
 * See the benchmark methodology note on 27.5yr vs 39yr classification.
 */
const RESIDUAL_CLASS_BY_PROPERTY_TYPE: Record<PropertyType, "27_5yr" | "39yr"> = {
  SINGLE_FAMILY_RENTAL: "27_5yr",
  SMALL_MULTIFAMILY: "27_5yr",
  MID_MULTIFAMILY: "27_5yr",
  SHORT_TERM_RENTAL: "39yr",
  COMMERCIAL: "39yr",
};

export interface ClassifyAssetsV2OrchestratorInput {
  studyId: string;
  propertyType: PropertyType;
  address: string;
  squareFeet: number | null;
  yearBuilt: number | null;
  acquiredAtIso: string;
  buildingValueCents: number;
  photos: Array<{
    documentId: string;
    filename: string;
    analysis: DescribePhotoOutput;
  }>;
  improvementLineItems: ClassifyAssetsV2Input["improvementLineItems"];
  /**
   * v2 Phase 7 slice 3 (ADR 0013). When present, the FIRST classifier
   * call is issued with this error embedded in the user prompt — the
   * model is instructed to correct the cited issues. Used by the
   * review-retry loop in `deliverAiReport` to thread content-blocker
   * findings back into the upstream step. Distinct from the internal
   * balance-retry `priorAttemptError` generated by `invoke`.
   */
  priorAttemptError?: string;
}

export interface ClassifyAssetsV2Result {
  /** Schedule with residual plug already applied — ready to persist. */
  schedule: ClassifyAssetsV2Output;
  attempts: number;
  balanced: boolean;
  balanceMessage?: string;
  residualCents: number;
}

/**
 * Step C (v2). Differences vs. v1:
 *   • Line items carry per-item physical/functional and global
 *     time/location multipliers with justifications.
 *   • The residual line item plugs the remainder to the building value
 *     instead of forcing the model to sum to exact cents.
 *   • Arithmetic check per line: adjustedCostCents must match quantity
 *     × unitCost × multipliers within ±$0.05.
 *   • Retries once on validation failure, same pattern as v1.
 */
export async function classifyAssetsV2(
  input: ClassifyAssetsV2OrchestratorInput,
): Promise<ClassifyAssetsV2Result> {
  const library = getAssetLibrary(input.propertyType);
  const residualClass = RESIDUAL_CLASS_BY_PROPERTY_TYPE[input.propertyType];
  const webSearchEnabled = isV2WebSearchEnabled();

  const basePromptInput: ClassifyAssetsV2Input = {
    propertyType: input.propertyType,
    address: input.address,
    squareFeet: input.squareFeet,
    yearBuilt: input.yearBuilt,
    acquiredAtIso: input.acquiredAtIso,
    buildingValueCents: input.buildingValueCents,
    residualClass,
    library,
    photos: input.photos,
    improvementLineItems: scrubPiiJson(input.improvementLineItems),
    webSearchEnabled,
    // Phase 7 slice 3: thread the review-driven priorAttemptError into
    // the first attempt's prompt. The internal balance-retry continues
    // to layer its own error on top if the first attempt also fails
    // the sum-check.
    priorAttemptError: input.priorAttemptError,
  };

  const first = await invoke(input.studyId, basePromptInput, 1, webSearchEnabled);
  const firstCheck = validateClassifyAssetsV2(first, input.buildingValueCents);
  if (firstCheck.ok) {
    const plugged = applyResidualPlug(first, input.buildingValueCents);
    return {
      schedule: plugged,
      attempts: 1,
      balanced: true,
      residualCents: firstCheck.residualCents,
    };
  }

  const second = await invoke(
    input.studyId,
    { ...basePromptInput, priorAttemptError: formatV2ValidationErrorForRetry(firstCheck) },
    2,
    webSearchEnabled,
  );
  const secondCheck = validateClassifyAssetsV2(second, input.buildingValueCents);
  const plugged = secondCheck.ok ? applyResidualPlug(second, input.buildingValueCents) : second;
  return {
    schedule: plugged,
    attempts: 2,
    balanced: secondCheck.ok,
    balanceMessage: secondCheck.ok ? undefined : secondCheck.message,
    residualCents: secondCheck.residualCents,
  };
}

async function invoke(
  studyId: string,
  promptInput: ClassifyAssetsV2Input,
  attempt: number,
  webSearchEnabled: boolean,
): Promise<ClassifyAssetsV2Output> {
  const serverTools: ServerTool[] = webSearchEnabled ? [WEB_SEARCH_TOOL] : [];
  const { output } = await callTool({
    operation: `classify-assets-v2:${studyId}:attempt-${attempt}`,
    promptVersion: CLASSIFY_ASSETS_V2_PROMPT_VERSION,
    model: MODELS.classifyAssets,
    system: CLASSIFY_ASSETS_V2_SYSTEM,
    userMessage: buildClassifyAssetsV2UserPrompt(promptInput),
    tool: CLASSIFY_ASSETS_V2_TOOL,
    outputSchema: classifyAssetsV2OutputSchema,
    serverTools,
    // Per-item output is meaty (6 multipliers + justifications × up to
    // 300 items). Worst observed: 5+ min Opus run truncated mid-JSON at
    // 16k, returning tool_use input without the `lineItems` field. Bump
    // to Opus 4.7's extended-output ceiling so real properties fit. Higher
    // when web_search is on to absorb search tool_use + result blocks.
    maxTokens: webSearchEnabled ? 48000 : 32768,
    studyId,
    inputDetails: {
      attempt,
      buildingValueCents: promptInput.buildingValueCents,
      photoCount: promptInput.photos.length,
      receiptCount: promptInput.improvementLineItems.length,
      webSearchEnabled,
    },
  });
  return output;
}
